-- Stage 1: initial public Store catalog seed.
-- No commercial pricing, MOQ, brand, origin or supplier claims are invented.
-- These records provide the initial catalog structure for the independent Store DB.

INSERT OR IGNORE INTO commerce_categories (
  id,
  parent_id,
  slug,
  name,
  status,
  created_at,
  updated_at
) VALUES
(
  'cat-fertilizers-crop-nutrition',
  NULL,
  'fertilizers-crop-nutrition',
  'Fertilizers & Crop Nutrition',
  'published',
  datetime('now'),
  datetime('now')
),
(
  'cat-crop-protection',
  NULL,
  'crop-protection',
  'Crop Protection',
  'published',
  datetime('now'),
  datetime('now')
),
(
  'cat-seeds-planting-material',
  NULL,
  'seeds-planting-material',
  'Seeds & Planting Material',
  'published',
  datetime('now'),
  datetime('now')
),
(
  'cat-agricultural-equipment',
  NULL,
  'agricultural-equipment',
  'Agricultural Equipment',
  'published',
  datetime('now'),
  datetime('now')
);

INSERT OR IGNORE INTO commerce_products (
  id,
  slug,
  name,
  brand,
  category_id,
  status,
  origin_country,
  moq,
  unit,
  availability_status,
  lead_time,
  price_visibility,
  currency,
  price_min,
  price_max,
  supply_capacity,
  incoterms,
  short_description,
  description,
  specifications_json,
  packaging,
  application,
  supplier_id,
  origin_statement,
  verification_level,
  verification_updated_at,
  created_at,
  updated_at,
  published_at
) VALUES
(
  'prod-npk-fertilizer',
  'npk-fertilizer',
  'NPK Fertilizer',
  NULL,
  'cat-fertilizers-crop-nutrition',
  'published',
  NULL,
  NULL,
  NULL,
  'on_request',
  NULL,
  'rfq',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Bulk / B2B fertilizer supply',
  'NPK fertilizer product record for commercial and technical agricultural requirements. Final grade, specification, packaging, quantity and supply conditions are confirmed through the inquiry process.',
  '{}',
  NULL,
  'Crop nutrition',
  NULL,
  NULL,
  'declared',
  NULL,
  datetime('now'),
  datetime('now'),
  datetime('now')
),
(
  'prod-micronutrient-blend',
  'micronutrient-blend',
  'Micronutrient Blend',
  NULL,
  'cat-fertilizers-crop-nutrition',
  'published',
  NULL,
  NULL,
  NULL,
  'on_request',
  NULL,
  'rfq',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Technical agricultural input request',
  'Micronutrient blend product record for crop nutrition requirements. Technical composition, grade, packaging and commercial conditions are confirmed through the inquiry process.',
  '{}',
  NULL,
  'Crop nutrition',
  NULL,
  NULL,
  'declared',
  NULL,
  datetime('now'),
  datetime('now'),
  datetime('now')
),
(
  'prod-agricultural-input',
  'agricultural-input',
  'Agricultural Input',
  NULL,
  'cat-crop-protection',
  'published',
  NULL,
  NULL,
  NULL,
  'on_request',
  NULL,
  'rfq',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Agricultural input for crop protection requirements',
  'Agricultural input product record for crop health and protection requirements. Product identity, technical specification, regulatory status and commercial conditions are confirmed before supply.',
  '{}',
  NULL,
  'Crop protection',
  NULL,
  NULL,
  'declared',
  NULL,
  datetime('now'),
  datetime('now'),
  datetime('now')
),
(
  'prod-planting-material',
  'planting-material',
  'Planting Material',
  NULL,
  'cat-seeds-planting-material',
  'published',
  NULL,
  NULL,
  NULL,
  'on_request',
  NULL,
  'rfq',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Seeds and planting material',
  'Planting material product record for commercial agricultural production. Variety, origin, certification, quantity, packaging and supply conditions are confirmed through the inquiry process.',
  '{}',
  NULL,
  'Seeds and planting material',
  NULL,
  NULL,
  'declared',
  NULL,
  datetime('now'),
  datetime('now'),
  datetime('now')
),
(
  'prod-farm-equipment',
  'farm-equipment',
  'Farm Equipment',
  NULL,
  'cat-agricultural-equipment',
  'published',
  NULL,
  NULL,
  NULL,
  'on_request',
  NULL,
  'rfq',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'Agricultural equipment and technical solutions',
  'Agricultural equipment product record for farm operations. Technical specifications, configuration, availability, delivery conditions and commercial terms are confirmed through the inquiry process.',
  '{}',
  NULL,
  'Farm operations',
  NULL,
  NULL,
  'declared',
  NULL,
  datetime('now'),
  datetime('now'),
  datetime('now')
);
